# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: DataDome Plugin Experimentation

type: middleware

# The import path of your plugin.
import: github.com/maximeroma/traefik-plugin-datadome

# A brief description of what your plugin is doing.
summary: A Traefik plugin to integrate DataDome bot protection.
iconPath: .assets/icon.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  endpoint: "api.datadome.co"
  dataServerSideKey: "your-server-side-key" # or set the DATADOME_SERVER_SIDE_KEY environment variable
